services:
#    quizz_admin.example:
#        class: Quizz\Bundle\AdminBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    quizz_admin.admin.question:
        class: Quizz\Bundle\AdminBundle\Admin\QuestionAdmin
        arguments: [~, Quizz\Bundle\AdminBundle\Entity\Question, QuizzAdminBundle:QuestionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Question}

    quizz_admin.admin.answer:
        class: Quizz\Bundle\AdminBundle\Admin\AnswerAdmin
        arguments: [~, Quizz\Bundle\AdminBundle\Entity\Answer, QuizzAdminBundle:AnswerAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Answer}
