<?php

namespace Quizz\Bundle\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DrugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrugRepository extends EntityRepository
{
}
