<?php

namespace Quizz\Bundle\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicationRepository extends EntityRepository
{
}
