sonata_admin:
    title:      Quizz Admin
    #title_logo: bundles/anchorventurescommon/img/favicon.ico

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks